CREATE TABLE Jobs (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  JobId NVARCHAR(50) UNIQUE,
  JobTitle NVARCHAR(255),
  Company NVARCHAR(255),
  Location NVARCHAR(255),
  Salary NVARCHAR(100),
  Description NVARCHAR(MAX),
  ApplyLink NVARCHAR(500),
  SearchKey NVARCHAR(100),
  PostedTime DATETIME NULL,
  Source NVARCHAR(50),
  MatchingScore DECIMAL(5,2) DEFAULT 0,
  Status NVARCHAR(20) DEFAULT 'Not Applied',
  CreatedAt DATETIME DEFAULT GETUTCDATE()
);

CREATE TABLE Resumes (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  FileName NVARCHAR(255),
  FilePath NVARCHAR(500),
  UploadedAt DATETIME DEFAULT GETUTCDATE(),
  IsActive BIT DEFAULT 1
);
